# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getArithmeticPutPrice <- function(nInt, strike, spot, vol, r, expiry, b, nReps) {
    .Call(`_OptionPricer_getArithmeticPutPrice`, nInt, strike, spot, vol, r, expiry, b, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_OptionPricer_rcpp_hello_world`)
}

